#!/bin/sh
set -x
switch=br0
if [ -n "$1" ];then
	ip tuntap add $1 mode tap user `whoami`
	ip link set $1 up
	sleep 0.5s
	sysctl -w net.ipv4.ip_forward=1
	route add -host 192.168.1.10 dev $1
	exit 0
else
	echo "Error: no interface specified"
	exit 1
fi
